name: Cypress Tests

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        id: install-dependencies
        run: npm install

      - name: Run E2E Tests Desktop
        id: e2e-desktop
        uses: cypress-io/github-action@v6
        with:
          command: npm run e2e-desktop-ci
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: Cypress E2E Desktop

      - name: Publish Desktop Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-desktop
          path: cucumber-report.html

      - name: Run E2E Tests Mobile
        id: e2e-mobile
        if: always()
        uses: cypress-io/github-action@v6
        with:
          command: npm run e2e-mobile-ci
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: Cypress E2E Mobile

      - name: Publish Mobile Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-mobile
          path: cucumber-report.html
        
