name: Cypress Tests

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: cypress-io/github-action@v6
        with:
          command: npm install
      - name: Cypress run e2e Desktop
        uses: cypress-io/github-action@v6
        with:
          command: npm run e2e-desktop-ci
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: Cypress E2E Desktop
      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-desktop
          path: cucumber-report.html
      - name: Cypress run e2e Mobile
        uses: cypress-io/github-action@v6
        with:
          command: npm run e2e-mobile-ci
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: Cypress E2E Mobile
      - name: Publish test results mobile
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-mobile
          path: cucumber-report.html
        
